#!/bin/bash
: '
parseAllPatients.sh
===================

Populate the WhatIsInIDS7 table in REDCap for a specific project using findscu. This script is part of a sequence of scripts: getAllPatients2.sh - parseAllPatients.sh - whatIsInIDS7.py.

- user: processing
- depends-on:
  - /tmp/parseAllPatients{projname}/
  - /tmp/pullStudies{projname}/
- log-file:
  - ${SERVERDIR}/logs/whatIsInIDS7{projname}.log,
- pid-file: ${SERVERDIR}/.pids/whatIsInIDS7{projname}.pid
- start: 
  */48 * * * * /usr/bin/flock -n /home/processing/.pids/getAllPatients2{projname}.pid /bin/bash -c "/home/processing/bin/utils/getAllPatients2.sh 10000 "{proejct}" >> /home/processing/logs/whatIsInIDS7/whatIsInIDS7{projname}.log 2>&1 \
  && /home/processing/bin/utils/parseAllPatients.sh "{projname}" >> /home/processing/logs/whatIsInIDS7/whatIsInIDS7{projname}.log 2>&1 \
  && /home/processing/bin/utils/whatIsInIDS7.py "{projname}" >> /home/processing/logs/whatIsInIDS7/whatIsInIDS7{projname}.log 2>&1"


Notes
-----

Depends on output generated by getAllPatients2.sh and provides input for whatIsInIDS7.sh (intermediate processing).

Get list of optional findscu entries from http://dicom.nema.org/medical/dicom/current/output/html/part04.html#sect_C.6.1.1

' #end-doc


InstitutionName=""
if [ "$#" -eq "1" ]; then
    InstitutionName="$1"
fi


containsElement () {
    local e match="$1"
    shift
    for e; do [[ "$e" == "$match" ]] && return 0; done
    return 1
}

echo "`date +'%Y-%m-%d %H:%M:%S.%06N'`: [parseAllPatients.sh] start ${InstitutionName}"
od="/tmp/allPatients${InstitutionName}/"
declare -a patientids
OLDIFS=$IFS
IFS=$'\n'
fileArray=($(find ${od} -type f))
IFS=${OLDIFS}
tLen=${#fileArray[@]}

for (( i=0; i<${tLen}; i++ )); do
    file="${fileArray[$i]}"
    DCMDICTPATH=/usr/share/dcmtk/dicom.dic
    pid=`dcmdump +P "PatientID" "${file}" | cut -d'[' -f2 | cut -d']' -f1`
    #echo $pid
    if ! containsElement "${pid}" "${patientids[@]}"; then
#	echo "skip"
#    else
      patientids+=("$pid")
      #echo ${patientids[@]}
    fi
done
echo "`date +'%Y-%m-%d %H:%M:%S.%06N'`: [parseAllPatients.sh] found ${#patientids[@]} unique ${InstitutionName} patient ids"

ps="/tmp/pullStudies${InstitutionName}"
if [ ! -d "${ps}" ]; then
    mkdir -p "${ps}"
else
    rm -fR "${ps}/"
    mkdir -p "${ps}"
fi
# for each patient id pull study level information
for (( i=0; i<${#patientids[@]}; i++ )); do
    pid="${patientids[$i]}"
    # get the studies for this patient
    mkdir "${ps}/$i"
    DCMDICTPATH=/usr/share/dcmtk/dicom.dic
    # number of study related series  (0020,1206)"
    # number of study related instances  (0020,1208)"
    # modalities in study (0008,0061)
    res=$(/usr/bin/findscu -v -aet FIONA -aec DICOM_QR_SCP --study -k 0008,0052=STUDY -k "PatientID=${pid}" -k "PatientName" -k "StudyInstanceUID" -k "(0020,1206)" -k "(0020,1208)" -k "StudyDescription" -k "InstitutionName" -k "(0008,0090)" -k "StudyDate" -k "StudyTime" -k "(0008,0061)" -od "${ps}/$i" -X +sr --repeat 2 vir-app5274.ihelse.net 7840 2>&1 | tr -d '\0' | tr -d '\n')
    #echo "`date +'%Y-%m-%d %H:%M:%S.%06N'`: [parseAllPatients.sh] pull study level information for ${pid}. Message: $res"
done
echo "`date +'%Y-%m-%d %H:%M:%S.%06N'`: [parseAllPatients.sh] done for ${InstitutionName}"
